name: Check Tests for Pull Request
on:
  pull_request:
    branches:
      - dev

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependecies
        run: yarn install

      - name: Check Unit Tests
        run: yarn test:coverage
