name: Unit Tests

on:
  pull_request:
    branches:
      - dev

defaults:
  run:
    working-directory: ./

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v2

      - run: yarn install

      - run: yarn test:coverage
