name: Unit Tests
on:
  push:
    branches:
      - dev
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn install

      - name: Build Coverage
        run: yarn test:coverage

      - name: Build production website
        run: yarn build
