name: GitHub Pages
on:
  push:
    branches:
      - dev

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Build coverage
        run: yarn test:coverage

      - name: Copy paste coverage to githubpage
        run: cp -r ./coverage/lcov-report ./.github/pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.github/pages
